const couponCode = {
  result: true,
  offers: [
    {
      lmdid: "119734",
      store: "firstcry",
      "offer text": "20% Off on Baby Gear & Nursery Range",
      title: "20% Off",
      description: "Valid on Baby Gear & Nursery Range",
      code: "FC20BGNR",
      categories: "Kids and Toddlers,Baby Care,Baby Gears",
      url: "http://www.firstcry.com/bikes,-ride-ons/7/90?scat=90%40~2852%40%40%40%40%40%40%40%40%401%400%4020%40%40%40%40%40%40%40%40%40%40",
      type: "Code",
      offer: "Offer",
      "offer value": "20%",
      status: "Active",
      startdate: "2016-05-24",
      enddate: "2016-05-26",
    },
    {
      lmdid: "115961",
      store: "firstcry",
      "offer text": "10% Off on All Diapers",
      title: "10% Off",
      description: "Valid on All Diapers",
      code: "FC10DPR",
      categories: "Kids and Toddlers,Baby Care",
      url: "http://www.firstcry.com/baby-diapers/1/27?ref2=topofferdiaper10cb2Feb&c=FC10DPR",
      type: "Code",
      offer: "Cashback",
      "offer value": "10%",
      status: "Active",
      startdate: "2016-05-10",
      enddate: "2016-12-22",
    },
    {
      lmdid: "118938",
      store: "firstcry",
      "offer text": "20% Off on all products",
      title: "20% Off",
      description: "Valid on all products (For Kotak bank Bank users only)",
      code: "FC20KOTAK",
      categories: "Fashion,Kids and Toddlers,Kids Fashion,School Stuff,Baby Care,Maternity,Baby Gears",
      url: "http://www.firstcry.com/",
      type: "Code",
      offer: "Offer",
      "offer value": "20%",
      status: "Active",
      startdate: "2016-05-20",
      enddate: "2016-05-26",
    },
    {
      lmdid: "118937",
      store: "firstcry",
      "offer text": "15% Off on all products",
      title: "15% Off",
      description: "Valid on all products (For Indus Ind Bank users only)",
      code: "FCIND15",
      categories:
        "Fashion,Mens Apparels,Womens Apparels,Watches,Ethnic Wear,Lingerie,Eyewear,Footwear,Handbags and Wallets,Jewellery,Fashion Accessories",
      url: "http://www.firstcry.com/",
      type: "Code",
      offer: "Offer",
      "offer value": "15%",
      status: "Active",
      startdate: "2016-05-20",
      enddate: "2016-05-26",
    },
    {
      lmdid: "118936",
      store: "firstcry",
      "offer text": "20% Off on Baby Gear",
      title: "20% Off",
      description: "Valid on Baby Gear",
      code: "MRBG20",
      categories: "Kids and Toddlers,Baby Gears",
      url: "http://www.firstcry.com/",
      type: "Code",
      offer: "Percentage-Off",
      "offer value": "20%",
      status: "Active",
      startdate: "2016-05-20",
      enddate: "2016-05-26",
    },
    {
      lmdid: "118935",
      store: "firstcry",
      "offer text": "15% Off For HDFC Bank Bank users only",
      title: "15% Off",
      description: "Valid For HDFC Bank Bank users only",
      code: "FC15HDFC",
      categories: "Kids and Toddlers,Kids Fashion,School Stuff,Baby Care,Maternity,Baby Gears",
      url: "http://www.firstcry.com/",
      type: "Code",
      offer: "Offer",
      "offer value": "15%",
      status: "Active",
      startdate: "2016-05-20",
      enddate: "2016-05-26",
    },
    {
      lmdid: "118934",
      store: "firstcry",
      "offer text": "15% Off on all products",
      title: "15% Off",
      description: "Valid on all products (For AXIS Bank users only. Max. discount of Rs.500)",
      code: "AXIS15FC",
      categories: "Kids and Toddlers,Kids Fashion,School Stuff,Baby Care,Maternity,Baby Gears",
      url: "http://www.firstcry.com/",
      type: "Code",
      offer: "Offer",
      "offer value": "15%",
      status: "Active",
      startdate: "2016-05-20",
      enddate: "2016-05-26",
    },
    {
      lmdid: "118933",
      store: "firstcry",
      "offer text": "Rs.300 Off on Selected Products",
      title: "Rs.300 Off",
      description: "Valid on Selected Products (On Min. Purchase of Rs.1299)",
      code: "FY300",
      categories: "Fashion,Kids and Toddlers,Kids Fashion,School Stuff,Baby Care,Maternity,Baby Gears",
      url: "http://www.firstcry.com/",
      type: "Code",
      offer: "Price-Off",
      "offer value": "Rs.300",
      status: "Active",
      startdate: "2016-05-20",
      enddate: "2016-05-26",
    },
    {
      lmdid: "118932",
      store: "firstcry",
      "offer text": "25% Off on Baby And Nursery Gear Products",
      title: "25% Off",
      description: "Valid on Baby And Nursery Gear Products",
      code: "MAY25BGNR",
      categories: "Kids and Toddlers,Baby Care,Baby Gears",
      url: "http://www.firstcry.com/",
      type: "Code",
      offer: "Percentage-Off",
      "offer value": "25%",
      status: "Active",
      startdate: "2016-05-20",
      enddate: "2016-05-26",
    },
    {
      lmdid: "115970",
      store: "firstcry",
      "offer text": "25% Off on Kids Clothes and Fashion Accessories",
      title: "25% Off",
      description: "Valid on Kids Clothes and Fashion Accessories (On Min. Purchase of Rs.750)",
      code: "FC25CFF",
      categories: "Fashion,Kids and Toddlers,Kids Fashion",
      url: "http://www.firstcry.com/clothes-and-fashion-accessories?ref2=topofferfcappl20",
      type: "Code",
      offer: "Percentage-Off",
      "offer value": "25%",
      status: "Active",
      startdate: "2016-05-10",
      enddate: "2017-01-01",
    },
    {
      lmdid: "115969",
      store: "firstcry",
      "offer text": "15% Off on Maternity Wear Lingerie",
      title: "15% Off",
      description: "Valid on Maternity Wear Lingerie (On Min. Purchase of Rs.750)",
      code: "FC15MWL",
      categories: "Fashion,Mens Apparels,Womens Apparels,Lingerie,Kids and Toddlers,Maternity",
      url: "http://www.firstcry.com/searchresult.aspx?sale=21&brandid=0&searchstring=brand@~222~231~229~230~232~382~383@B@@1@0@21@@@@@@@@@@@@@@@@&sort=Popularity&ref2=topofferfcMatwr15&c=FC15MWL",
      type: "Code",
      offer: "Percentage-Off",
      "offer value": "15%",
      status: "Active",
      startdate: "2016-05-10",
      enddate: "2017-01-01",
    },
    {
      lmdid: "115968",
      store: "firstcry",
      "offer text": "15% Off on Birthday & Gifts",
      title: "15% Off",
      description: "Valid on Birthday & Gifts (On Min. Purchase of Rs.751)",
      code: "FC15BDAY",
      categories: "Gift Items",
      url: "http://www.firstcry.com/baby-kids-gifts?ref2=topofferfcbdaygfts15&c=FC15BDAY",
      type: "Code",
      offer: "Percentage-Off",
      "offer value": "15%",
      status: "Active",
      startdate: "2016-05-10",
      enddate: "2017-01-01",
    },
    {
      lmdid: "115967",
      store: "firstcry",
      "offer text": "20% Off on Books, CD's & School Supplies",
      title: "20% Off",
      description: "Valid on Books, CD's & School Supplies",
      code: "FC20BKSS",
      categories: "Entertainment,CDs Books and Magazine,Kids and Toddlers,School Stuff",
      url: "http://www.firstcry.com/back-to-school/10/0/0?ref2=topofferfcbcdschool20&c=FC20BKSS",
      type: "Code",
      offer: "Percentage-Off",
      "offer value": "20%",
      status: "Active",
      startdate: "2016-05-10",
      enddate: "2017-01-01",
    },
    {
      lmdid: "115966",
      store: "firstcry",
      "offer text": "15% Off on Baby Gear & Nursery",
      title: "15% Off",
      description: "Valid on Baby Gear & Nursery",
      code: "FC15BGNS",
      categories: "Kids and Toddlers,Baby Care,Baby Gears",
      url: "http://www.firstcry.com/baby-gear-and-nursery?ref2=topofferfcbgn15&c=FC15BGNS",
      type: "Code",
      offer: "Percentage-Off",
      "offer value": "15%",
      status: "Active",
      startdate: "2016-05-10",
      enddate: "2017-01-01",
    },
    {
      lmdid: "113460",
      store: "firstcry",
      "offer text": "10% Off on Diapering Essentials",
      title: "10% Off",
      description:
        "Valid on Diapering Essentials (On Min. Purchase of Rs.750. Max. once per user, Not valid on Baby Diapers and the brands)",
      code: "MAYAFDP10",
      categories: "Fashion,Kids and Toddlers,Kids Fashion,Baby Care,Baby Gears",
      url: "http://www.firstcry.com/diapering",
      type: "Code",
      offer: "Offer",
      "offer value": "10%",
      status: "Active",
      startdate: "2016-05-01",
      enddate: "2016-06-01",
    },
    {
      lmdid: "115965",
      store: "firstcry",
      "offer text": "15% discount on Toys and Gaming",
      title: "15% discount",
      description: "Valid on Toys and Gaming (on orders of Rs.750+)",
      code: "FC15TOY",
      categories: "Entertainment,Gaming,Board Games and Toys",
      url: "http://www.firstcry.com/baby-kids-toys-store?ref2=topofferdcfctyg15&c=FC15TOY",
      type: "Code",
      offer: "Percentage-Off",
      "offer value": "15%",
      status: "Active",
      startdate: "2016-05-10",
      enddate: "2017-01-01",
    },
    {
      lmdid: "113459",
      store: "firstcry",
      "offer text": "5% Off On Min. Purchase of Rs.1000",
      title: "5% Off",
      description:
        "Valid On Min. Purchase of Rs.1000 (Max. discount of Rs.800, not be valid on Diapers, Bottles & Accessories and Formula & Supplements & Selected brands)",
      code: "MAYAFAD5",
      categories: "Kids and Toddlers,Kids Fashion,School Stuff,Baby Care,Maternity,Baby Gears",
      url: "http://www.firstcry.com/",
      type: "Code",
      offer: "Offer",
      "offer value": "5%",
      status: "Active",
      startdate: "2016-05-01",
      enddate: "2016-06-01",
    },
    {
      lmdid: "115964",
      store: "firstcry",
      "offer text": "15% Off on Bath, Skin & Health Care",
      title: "15% Off",
      description: "Valid on Bath, Skin & Health Care",
      code: "FC15BSHS",
      categories: "Health and Beauty,Body Care",
      url: "http://www.firstcry.com/bath-skin-and-health-care?ref2=topofferfcbsh15&c=FC15BSHS",
      type: "Code",
      offer: "Percentage-Off",
      "offer value": "15%",
      status: "Active",
      startdate: "2016-05-10",
      enddate: "2017-01-01",
    },
    {
      lmdid: "115963",
      store: "firstcry",
      "offer text": "20% Off on Feeding & Nursing",
      title: "20% Off",
      description: "Valid on Feeding & Nursing",
      code: "FC20FDNR",
      categories: "Kids and Toddlers,Baby Care",
      url: "http://www.firstcry.com/feeding-and-nursing?ref2=topofferfcfn20&c=FC20FDNR",
      type: "Code",
      offer: "Percentage-Off",
      "offer value": "20%",
      status: "Active",
      startdate: "2016-05-10",
      enddate: "2017-01-01",
    },
    {
      lmdid: "115962",
      store: "firstcry",
      "offer text": "10% Off on Diapering Essentials",
      title: "10% Off",
      description: "Valid on Diapering Essentials",
      code: "FC10DPRG",
      categories: "Kids and Toddlers,Baby Care",
      url: "http://www.firstcry.com/diapering?ref2=topoffersdcfcdp10&c=FC10DPRG",
      type: "Code",
      offer: "Percentage-Off",
      "offer value": "10%",
      status: "Active",
      startdate: "2016-05-10",
      enddate: "2017-01-01",
    },
    {
      lmdid: "113961",
      store: "firstcry",
      "offer text": "90% Off on Handpicked Products",
      title: "90% Off",
      description: "Valid on Handpicked Products (Max. once per user)",
      code: "MAYAFFHP90",
      categories: "Fashion,Kids and Toddlers,Kids Fashion,School Stuff,Baby Care,Maternity,Baby Gears",
      url: "http://www.firstcry.com/featuredoffers.aspx?cpid=772",
      type: "Code",
      offer: "Offer",
      "offer value": "90%",
      status: "Active",
      startdate: "2016-05-02",
      enddate: "2016-06-02",
    },
    {
      lmdid: "113960",
      store: "firstcry",
      "offer text": "15% Off on All Products",
      title: "15% Off",
      description:
        "Valid on All Products (Max. discount of Rs.500, Not valid on Diaper, Combos Bottles & Accessories, Bottle Cleaning & Sterilisation and Formula & supplements and Selected brands)",
      code: "MAYAFFLT15",
      categories: "Fashion,Kids and Toddlers,Kids Fashion,School Stuff,Baby Care,Maternity,Baby Gears",
      url: "http://www.firstcry.com/",
      type: "Code",
      offer: "Offer",
      "offer value": "15%",
      status: "Active",
      startdate: "2016-05-02",
      enddate: "2016-06-02",
    },
    {
      lmdid: "91774",
      store: "firstcry",
      "offer text": "27% Discount on Apparels",
      title: "27% Discount",
      description: "Valid on Apparels (Min. purchase of Rs.750. Not valid on Few Brands)",
      code: "FCAPP27",
      categories: "Kids and Toddlers,Kids Fashion",
      url: "http://www.firstcry.com/clothes-and-fashion-accessories",
      type: "Code",
      offer: "Percentage-Off",
      "offer value": "27%",
      status: "Active",
      startdate: "2016-01-20",
      enddate: "2016-05-29",
    },
    {
      lmdid: "113959",
      store: "firstcry",
      "offer text": "Rs.300 Off On Min. Purchase of Rs.1500",
      title: "Rs.300 Off",
      description:
        "Valid On Min. Purchase of Rs.1500 (Not valid on Diapers, Combos, Bottles & Accessories, Bottle Cleaning & Sterilisation and Formula & supplements and Selected brands)",
      code: "MAYAFF300",
      categories: "Fashion,Kids and Toddlers,Kids Fashion,School Stuff,Baby Care,Maternity,Baby Gears",
      url: "http://www.firstcry.com/",
      type: "Code",
      offer: "Offer",
      "offer value": "Rs.300",
      status: "Active",
      startdate: "2016-05-02",
      enddate: "2016-06-02",
    },
    {
      lmdid: "113958",
      store: "firstcry",
      "offer text": "Rs.200 Off on premium brands",
      title: "Rs.200 Off",
      description:
        "Valid on premium brands (On Min. Purchase of Rs.1100. Max. once per user, Max. once per user, Not valid on Combos, Bottles & Accessories and Formula & Supplements)",
      code: "MAYAFP200",
      categories: "Fashion,Kids and Toddlers,Kids Fashion,School Stuff,Baby Care,Maternity,Baby Gears",
      url: "http://www.firstcry.com/",
      type: "Code",
      offer: "Offer",
      "offer value": "Rs.200",
      status: "Active",
      startdate: "2016-05-02",
      enddate: "2016-06-02",
    },
  ],
};

export { couponCode };
